### ISSUE TITLE
Scraping is violation of terms of use

### ISSUE THREAD

**Issue by dkensok** [bulam/ZIP-scraper#1]
It is a violation of Esri's terms of use for its online services to scrape content.

http://downloads2.esri.com/ArcGISOnline/docs/tou_summary.pdf
http://www.esri.com/~/media/Files/Pdfs/legal/pdfs/e300
**2.4 Prohibited Uses of the Online Services**
(vii) manually or systematically collect or scrape (screen or web scraping) Content from Online Services

**Comment by bulam** [comment]
Apologies! I wasn't aware of the terms. I mostly wrote the script to learn
how to write a scraping script in general and haven't actually used it
much. I have removed all references to the Esri website and modified the
code to make it just a general framework script not specific to any website.

On Mon, Feb 29, 2016 at 11:31 AM, dkensok notifications@github.com wrote:

> It is a violation of Esri's terms of use for it online services to scrape
> content.
> 
> http://downloads2.esri.com/ArcGISOnline/docs/tou_summary.pdf
> http://www.esri.com/~/media/Files/Pdfs/legal/pdfs/e300
> _2.4 Prohibited Uses of the Online Services_
> (vii) manually or systematically collect or scrape (screen or web
> scraping) Content from Online Services
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bulam/ZIP-scraper/issues/1.

## 

Bilguun Ulammandakh

**Comment by dkensok** [comment]
Thank you for the quick response and update to the script.
